#!/usr/bin/env python
# -*- coding: utf-8 -*-

# the commented-out topics don't result in the expected chapter and need to be put in manually
import keyboard
import time

top100 = [
    "Diabetes mellitus",
    "Mammakarzinom",
    "Lungenkarzinom",
    "Ischämischer Schlaganfall",
    "Ovarialtumoren",
    "Divertikulose und Divertikulitis",
    "Kolorektales Karzinom",
    "Meningitis",
    "Pneumonie",
    "Morbus Crohn",
    "Lungenembolie",
    "Arterielle Hypertonie",
    "Anorexia nervosa",
    "Allergische Erkrankungen",
    "Pneumothorax",
    "Zytostatika",
    "Multiple Sklerose",
    "Bandscheibenprolaps",
    "Vigilanzminderung und intrakranielle Volumenzunahme",
    "Phlebothrombose",
    "Herzinsuffizienz",
    "Myokardinfarkt",
    "Nosokomiale Infektionen",
    "Tuberkulose",
    "Vorhofflimmern",
    "Epilepsie",
    "Depression",
    "Bösartige Knochentumoren",
    "Reaktionen auf schwere Belastungen und Anpassungsstörungen",
    "Hyperthyreose",
    "Polymyalgia rheumatica und Riesenzellarteriitis",
    "Periphere arterielle Verschlusskrankheit",
    "Angeborene Herzfehler",
    "Rettungsablauf am Unfallort und klinische Primärversorgung",
    "Lyme-Borreliose",
    "Antidepressiva",
    "Rheumatoide Arthritis",
    "HIV",
    "Reanimation",
    "Sepsis",
    "Leberzirrhose",
    "Infektiöse Endokarditis",
    "Weichteilläsionen der Schulter",
    "Chronisch obstruktive Lungenerkrankung",
    "Sarkoidose",
    "Psychopathologischer Befund",
    "Magenkarzinom",
    "Antibiotika - Übersicht",
    "Akute Leukämien",
    "Sterilität, Infertilität und Impotenz",
    "Pankreaskarzinom",
    "Asthma bronchiale",
    "Neurologische Untersuchung",
    "Appendizitis",
    "Hepatitis B",
    "Subarachnoidalblutung",
    "Antipsychotika",
    "Infektiöse Mononukleose",
    "Cholelithiasis, Cholezystitis und Cholangitis",
    "Morbus Perthes",
    "Psoriasis vulgaris",
    "Parkinson-Syndrom und Morbus Parkinson",
    "Epidemiologie und Wahrscheinlichkeiten",
    "Studientypen der medizinischen Forschung",
    "Schock",
    "Nicht-orale Antikoagulation",
    "Gesetzliche Krankenversicherung",
    "Chronische Niereninsuffizienz",
    "Juvenile idiopathische Arthritis",
    "Nebennierenrindeninsuffizienz",
    "Urolithiasis",
    "Angststörungen und Phobien",
    "Endometriose",
    "Immunsuppressiva",
    "Osteoporose",
    "Wirbelkörperfraktur",
    "Kindesmisshandlung",
    "Alkohol (Intoxikation und Abhängigkeit)",
    "Ärztliche Rechtskunde",
    "Diagnostik in der Gynäkologie",
    "Psychotherapeutische Verfahren (Klinik)",
    "Cushing-Syndrom",
    "Allgemeinanästhesie",
    "Morbus Bechterew",
    "Systemischer Lupus erythematodes",
    "Glutensensitive Enteropathie",
    "Akute Pankreatitis",
    "Morbus Alzheimer",
    "Urothelkarzinom",
    "Tiefgreifende Entwicklungsstörungen",
    "Strangulation und Ersticken",
    "Antidiabetika",
    "Influenza",
    "Nierenzellkarzinom",
    "Guillain-Barré-Syndrom",
    "Hyperurikämie und Gicht",
    "Wundbehandlung",
    "Erkrankungen durch organische Lösungsmittel, Insektizide, Halogenkohlenwasserstoffe, Benzol und Homologe",
    "Prävention",
    "Gesetzliche Unfallversicherung"
]

top100search = [
    "mellitus",
    "Mammakarzinom",
    "Lungenkarzinom",
    "Schlaganfall",
    "Ovarialtumoren",
    "Divertikulitis",
    "Kolorektales",
    "Meningitis",
    "Pneumonie",
    "Crohn",
    "Lungenembolie",
    "Hypertonie",
    "Anorexia",
    "Allergische",
    "Pneumothorax",
    "Zytostatika",
    "Multiple",
    "Bandscheibenprolaps",
    "Vigilanzminderung",
    "Phlebothrombose",
    "Herzinsuffizienz",
    "Myokardinfarkt",
    "Nosokomiale",
    "Tuberkulose",
    "Vorhofflimmern",
    "Epilepsie",
    "Depression",
    "Knochentumoren",
    "Anpassungsstörungen",
    "Hyperthyreose",
    "Riesenzellarteriitis",
    # "Verschlusskrankheit",
    "Angeborene ",
    "Rettungsablauf",
    "Lyme-Borreliose",
    "Antidepressiva",
    "Rheumatoide",
    "HIV",
    "Reanimation",
    "Sepsis",
    "Leberzirrhose",
    "Endokarditis",
    "Weichteilläsionen",
    "obstruktive",
    "Sarkoidose",
    "Psychopathologischer",
    "Magenkarzinom",
    "Antibiotika",
    "Leukämien",
    "Impotenz",
    "Pankreaskarzinom",
    "Asthma",
    "Neurologische",
    "Appendizitis",
    # "Hepatitis B",
    "Subarachnoidalblutung",
    "Antipsychotika",
    "Mononukleose",
    "Cholelithiasis",
    "Perthes",
    # "Psoriasis",
    # "Parkinson-Syndrom",
    "Wahrscheinlichkeiten",
    "Studientypen",
    "Schock",
    "Nicht-orale",
    "Krankenversicherung",
    "Niereninsuffizienz",
    "Juvenile",
    "Nebennierenrindeninsuffizienz",
    "Urolithiasis",
    "Angststörungen",
    "Endometriose",
    "Immunsuppressiva",
    "Osteoporose",
    "Wirbelkörperfraktur",
    "Kindesmisshandlung",
    "Alkohol",
    "Ärztliche",
    "Gynäkologie",
    "Psychotherapeutische",
    "Cushing-Syndrom",
    "Allgemeinanästhesie",
    "Bechterew",
    "Systemischer",
    "Glutensensitive",
    "Pankreatitis",
    "Alzheimer",
    "Urothelkarzinom",
    "Tiefgreifende",
    "Strangulation",
    "Antidiabetika",
    "Influenza",
    "Nierenzellkarzinom",
    "Guillain-Barré-Syndrom",
    "Hyperurikämie",
    "Wundbehandlung",
    "Halogenkohlenwasserstoffe",
    "Prävention",
    "Unfallversicherung",
]

time.sleep(5)
for x in top100search:
    keyboard.write(x)
    time.sleep(0.2)
    keyboard.press_and_release('return')
    time.sleep(0.2)
